version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: protocols_postgres
    environment:
      POSTGRES_DB: protocols
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-network

  app:
    build: .
    container_name: protocols_app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      HOSTNAME: "0.0.0.0"
      DATABASE_URL: postgresql://postgres:password@postgres:5432/protocols
    depends_on:
      postgres:
        condition: service_healthy
    command: ["sh", "-c", "npx drizzle-kit push && npm run build && npm start"]
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge