import type { Metadata } from 'next';
import './globals.css';
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar';
import { AppSidebar } from '@/components/custom/sidebar';
import { Toaster } from '@/components/ui/sonner';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className="overflow-hidden">
        <SidebarProvider>
          <AppSidebar />
          <div className="bg-sidebar/80 h-dvh border-r p-2">
            <SidebarTrigger />
          </div>
          <main className="h-dvh w-full overflow-hidden">{children}</main>
          <Toaster richColors />
        </SidebarProvider>
      </body>
    </html>
  );
}
